"""
Kohler AquaSense OS - Analytics & ML Engine
-------------------------------------------
Processes streaming IoT telemetry and detects:

1. Continuous micro-leaks
2. Statistical flow anomalies using rolling Z-score
3. ML anomalies using Isolation Forest
4. Dynamic hygiene breaches

Input:
    Telemetry dictionary / JSON object generated by simulator.py

Output:
    Anomaly payload dictionary
"""

from collections import defaultdict, deque
from statistics import mean, stdev

from sklearn.ensemble import IsolationForest


# ============================================================
# CONFIGURATION
# ============================================================

ROLLING_WINDOW = 20

LEAK_FLOW_THRESHOLD = 0.25
LEAK_TICKS_REQUIRED = 5

Z_SCORE_THRESHOLD = 2.5

HYGIENE_BREACH_THRESHOLD = 30


# ============================================================
# STREAMING STATE
# ============================================================

# Flow history for each fixture.
_flow_history = defaultdict(
    lambda: deque(maxlen=ROLLING_WINDOW)
)

# Number of consecutive leak-like ticks for each fixture.
_leak_streak = defaultdict(int)

# Store recent feature vectors for each fixture.
_feature_history = defaultdict(
    lambda: deque(maxlen=ROLLING_WINDOW)
)


# ============================================================
# HELPER: ROLLING Z-SCORE
# ============================================================

def calculate_z_score(value, history):
    """
    Calculate the rolling Z-score of a value.

    z = (x - mean) / standard deviation

    Returns
    -------
    float
        Z-score. Returns 0.0 when insufficient variance exists.
    """

    if len(history) < 2:
        return 0.0

    avg = mean(history)
    std = stdev(history)

    if std == 0:
        return 0.0

    return (value - avg) / std


# ============================================================
# HELPER: ISOLATION FOREST
# ============================================================

def detect_ml_anomaly(fixture_id, features):
    """
    Detect statistical anomalies using Isolation Forest.

    Parameters
    ----------
    fixture_id : str
        Fixture identifier.

    features : list
        Feature vector containing:
        [water_flow, flush_count, occupancy, pressure]

    Returns
    -------
    bool
        True if the current observation is anomalous.
    """

    history = _feature_history[fixture_id]

    # Isolation Forest requires multiple observations to
    # establish a meaningful anomaly boundary.
    if len(history) < 5:
        history.append(features)
        return False

    model = IsolationForest(
        n_estimators=100,
        contamination=0.10,
        random_state=42
    )

    model.fit(list(history))

    prediction = model.predict([features])[0]

    history.append(features)

    return prediction == -1


# ============================================================
# HELPER: LEAK DETECTION
# ============================================================

def detect_continuous_leak(fixture_id, water_flow, occupancy):
    """
    Detect a continuous micro-leak.

    A leak is considered present when:

        water_flow > 0.25 LPM
        AND
        occupancy == 0

    for more than 5 consecutive ticks.
    """

    if water_flow > LEAK_FLOW_THRESHOLD and occupancy == 0:
        _leak_streak[fixture_id] += 1
    else:
        _leak_streak[fixture_id] = 0

    return _leak_streak[fixture_id] > LEAK_TICKS_REQUIRED


# ============================================================
# HELPER: DYNAMIC HYGIENE INDEX
# ============================================================

def calculate_hygiene_score(occupancy, flush_count):
    """
    Calculate the Dynamic Hygiene Index.
    Unserviced occupancy lowers score; flushes restore score.

    Score:

        100
        - (0.6 * occupancy)
        + (0.8 * flush_count)

    The score is constrained to the range 0-100.
    """

    score = 100 - (0.6 * occupancy) + (0.8 * flush_count)

    return round(max(0.0, min(100.0, score)), 2)


# ============================================================
# MAIN ANALYTICS FUNCTION
# ============================================================

def analyze_tick(tick_json):
    """
    Analyze one streaming telemetry tick.

    Parameters
    ----------
    tick_json : dict
        Telemetry object produced by simulator.py.

    Returns
    -------
    dict
        Anomaly/analytics payload.
    """

    fixture_id = tick_json["fixture_id"]

    water_flow = float(tick_json["water_flow_lpm"])
    occupancy = int(tick_json["occupancy_count_10m"])
    flush_count = int(tick_json["flush_count_10m"])
    pressure = float(tick_json["pressure_psi"])

    # --------------------------------------------------------
    # 1. Rolling baseline Z-score
    # --------------------------------------------------------

    history = _flow_history[fixture_id]

    z_score = calculate_z_score(
        water_flow,
        list(history)
    )

    # Add current observation after calculating its score.
    history.append(water_flow)

    z_anomaly = abs(z_score) >= Z_SCORE_THRESHOLD

    # --------------------------------------------------------
    # 2. Continuous leak detection
    # --------------------------------------------------------

    continuous_leak = detect_continuous_leak(
        fixture_id,
        water_flow,
        occupancy
    )

    # --------------------------------------------------------
    # 3. Isolation Forest
    # --------------------------------------------------------

    features = [
        water_flow,
        flush_count,
        occupancy,
        pressure
    ]

    ml_anomaly = detect_ml_anomaly(
        fixture_id,
        features
    )

    # --------------------------------------------------------
    # 4. Dynamic Hygiene Index
    # --------------------------------------------------------

    hygiene_score = calculate_hygiene_score(
        occupancy,
        flush_count
    )

    hygiene_breach = (
        hygiene_score < HYGIENE_BREACH_THRESHOLD
    )

    # --------------------------------------------------------
    # 5. Determine anomaly codes
    # --------------------------------------------------------

    anomaly_codes = []

    if continuous_leak:
        anomaly_codes.append("ERR_CONTINUOUS_LEAK")

    if z_anomaly:
        anomaly_codes.append("ERR_FLOW_ZSCORE")

    if ml_anomaly:
        anomaly_codes.append("ERR_ML_ANOMALY")

    if hygiene_breach:
        anomaly_codes.append("HYGIENE_BREACH")

    # --------------------------------------------------------
    # 6. Overall status
    # --------------------------------------------------------

    status = (
        "ANOMALY"
        if anomaly_codes
        else "NORMAL"
    )

    # --------------------------------------------------------
    # 7. Return clean analytics payload
    # --------------------------------------------------------

    return {
        "timestamp": tick_json["timestamp"],
        "zone_id": tick_json["zone_id"],
        "fixture_id": fixture_id,

        "analytics": {
            "water_flow_lpm": water_flow,
            "rolling_z_score": round(z_score, 3),
            "ml_anomaly": ml_anomaly,

            "leak_streak": _leak_streak[fixture_id],
            "continuous_leak": continuous_leak,

            "occupancy_count_10m": occupancy,
            "flush_count_10m": flush_count,

            "hygiene_score": hygiene_score,
            "hygiene_breach": hygiene_breach,

            "pressure_psi": pressure
        },

        "status": status,
        "anomaly_codes": anomaly_codes
    }


# ============================================================
# RESET STATE
# ============================================================

def reset_analytics_state():
    """
    Clear all streaming analytics state.

    Useful when restarting a simulation or during testing.
    """

    _flow_history.clear()
    _leak_streak.clear()
    _feature_history.clear()


# ============================================================
# TEST BLOCK
# ============================================================

if __name__ == "__main__":

    # Import the synthetic telemetry generator.
    from backend.simulator import generate_telemetry_tick

    print("Kohler AquaSense Analytics Test\n")

    fixture = "KOHLER_FAUCET_101"

    # --------------------------------------------------------
    # Normal telemetry
    # --------------------------------------------------------

    print("--- NORMAL ---")

    for _ in range(3):

        tick = generate_telemetry_tick(
            zone_id="PNQ_NITB_DEPARTURE_ZONE_3",
            fixture_id=fixture,
            anomaly_mode="NORMAL"
        )

        result = analyze_tick(tick)

        print(result)

    # --------------------------------------------------------
    # Leak telemetry
    # --------------------------------------------------------

    print("\n--- LEAK TEST ---")

    for _ in range(7):

        tick = generate_telemetry_tick(
            zone_id="PNQ_NITB_DEPARTURE_ZONE_3",
            fixture_id=fixture,
            anomaly_mode="LEAK"
        )

        result = analyze_tick(tick)

        print(
            f"Flow={tick['water_flow_lpm']} LPM | "
            f"Occupancy={tick['occupancy_count_10m']} | "
            f"Leak Streak={result['analytics']['leak_streak']} | "
            f"Status={result['status']} | "
            f"Codes={result['anomaly_codes']}"
        )